// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPX3h1JehIDSm44Wvrr379oDytJFsXLh4',
    appId: '1:168474811239:web:cb80dca1e03cbfd652edc2',
    messagingSenderId: '168474811239',
    projectId: 'gomarket-9c61f',
    authDomain: 'gomarket-9c61f.firebaseapp.com',
    storageBucket: 'gomarket-9c61f.appspot.com',
    measurementId: 'G-8GBQ86NXRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWl6CEtKj0LGDVamSR7g1NvCQoLTffZvw',
    appId: '1:168474811239:android:a05fdc4037dbd9a952edc2',
    messagingSenderId: '168474811239',
    projectId: 'gomarket-9c61f',
    storageBucket: 'gomarket-9c61f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKmxb5gUJOSSeVguks-ZErMWC9wLSpFrg',
    appId: '1:168474811239:ios:15fdd62a554fa0a452edc2',
    messagingSenderId: '168474811239',
    projectId: 'gomarket-9c61f',
    storageBucket: 'gomarket-9c61f.appspot.com',
    iosBundleId: 'com.example.gomarketapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKmxb5gUJOSSeVguks-ZErMWC9wLSpFrg',
    appId: '1:168474811239:ios:15fdd62a554fa0a452edc2',
    messagingSenderId: '168474811239',
    projectId: 'gomarket-9c61f',
    storageBucket: 'gomarket-9c61f.appspot.com',
    iosBundleId: 'com.example.gomarketapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPX3h1JehIDSm44Wvrr379oDytJFsXLh4',
    appId: '1:168474811239:web:4fdd678830d690e152edc2',
    messagingSenderId: '168474811239',
    projectId: 'gomarket-9c61f',
    authDomain: 'gomarket-9c61f.firebaseapp.com',
    storageBucket: 'gomarket-9c61f.appspot.com',
    measurementId: 'G-6YL4PVPS60',
  );
}
